export type NiatCollege = { name: string; location: string };

// Verified against NIAT's official Collaborating Institutions directory.
export const NIAT_COLLEGES: NiatCollege[] = [
  { name: "GMR Institute of Technology", location: "Vizianagaram" },
  { name: "Ajeenkya DY Patil University", location: "Pune" },
  { name: "Sanjay Ghodawat University", location: "Kolhapur" },
  { name: "Noida International University", location: "Delhi NCR" },
  { name: "SMR University", location: "Hyderabad" },
  { name: "Sushant University", location: "Gurgaon" },
  { name: "Visakha Institute of Engineering & Technology", location: "Visakhapatnam" },
  { name: "PK DAS Institute of Social Sciences, Health Sciences & Technology", location: "Coimbatore" },
  { name: "Lingaya’s Institute of Management and Technology", location: "Vijayawada" },
  { name: "MVR College of Engineering and Technology", location: "Krishna" },
  { name: "Bharath Institute of Higher Education and Research", location: "Chennai" },
  { name: "St. Peter’s Institute of Higher Education and Research (SPIHER)", location: "Chennai" },
  { name: "Lingaya’s Vidyapeeth", location: "Faridabad" },
  { name: "Sri Sri University", location: "Cuttack" },
  { name: "T.S Mishra University", location: "Lucknow" },
  { name: "Subharti University", location: "Meerut" },
  { name: "SNS College of Technology", location: "Coimbatore" },
  { name: "Chaitanya (Deemed to be University)", location: "Hyderabad" },
  { name: "Geeta University", location: "Panipat" },
  { name: "S-VYASA University School of Advanced Studies", location: "Bengaluru" },
  { name: "Yenepoya Bangalore", location: "Bangalore" },
  { name: "AMET University", location: "Chennai" },
  { name: "Yenepoya University", location: "Mangalore" },
  { name: "Vivekananda Global University", location: "Jaipur" },
  { name: "St. Peter’s Institute of Higher Education and Research (SPIHER)", location: "Bangalore" },
  { name: "B. S. Abdur Rahman Crescent Institute of Science & Technology", location: "Chennai" },
  { name: "Annamacharya University", location: "Kadapa" },
  { name: "Sandip University", location: "Maharashtra" },
  { name: "Nadimpalli Satyanarayana Raju Institute of Technology (NSRIT)", location: "Visakhapatnam" },
  { name: "Scope Global Skills University", location: "Bhopal" },
  { name: "Alard University", location: "Pune" },
  { name: "Joy University", location: "Tirunelveli" },
  { name: "BEST Innovation University", location: "Anantapur" },
  { name: "Takshashila University", location: "Chennai–Pondicherry" },
  { name: "Chalapathi Institute of Technology", location: "Guntur" },
  { name: "Sanskriti University", location: "Mathura, Uttar Pradesh" },
  { name: "Aurora Deemed University", location: "Hyderabad" },
];