/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChooseCollegeRouteImport } from './routes/choose-college'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as GamesColorChakraRouteImport } from './routes/games.color-chakra'
import { Route as GamesDivineAimRouteImport } from './routes/games.divine-aim'
import { Route as GamesGaneshRhythmRouteImport } from './routes/games.ganesh-rhythm'
import { Route as GamesTempleRunRouteImport } from './routes/games.temple-run'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseCollegeRoute = ChooseCollegeRouteImport.update({
  id: '/choose-college',
  path: '/choose-college',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesColorChakraRoute = GamesColorChakraRouteImport.update({
  id: '/games/color-chakra',
  path: '/games/color-chakra',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesDivineAimRoute = GamesDivineAimRouteImport.update({
  id: '/games/divine-aim',
  path: '/games/divine-aim',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGaneshRhythmRoute = GamesGaneshRhythmRouteImport.update({
  id: '/games/ganesh-rhythm',
  path: '/games/ganesh-rhythm',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesTempleRunRoute = GamesTempleRunRouteImport.update({
  id: '/games/temple-run',
  path: '/games/temple-run',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/choose-college': typeof ChooseCollegeRoute
  '/profile': typeof ProfileRoute
  '/games/color-chakra': typeof GamesColorChakraRoute
  '/games/divine-aim': typeof GamesDivineAimRoute
  '/games/ganesh-rhythm': typeof GamesGaneshRhythmRoute
  '/games/temple-run': typeof GamesTempleRunRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/choose-college': typeof ChooseCollegeRoute
  '/profile': typeof ProfileRoute
  '/games/color-chakra': typeof GamesColorChakraRoute
  '/games/divine-aim': typeof GamesDivineAimRoute
  '/games/ganesh-rhythm': typeof GamesGaneshRhythmRoute
  '/games/temple-run': typeof GamesTempleRunRoute
  '/games': typeof GamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/choose-college': typeof ChooseCollegeRoute
  '/profile': typeof ProfileRoute
  '/games/color-chakra': typeof GamesColorChakraRoute
  '/games/divine-aim': typeof GamesDivineAimRoute
  '/games/ganesh-rhythm': typeof GamesGaneshRhythmRoute
  '/games/temple-run': typeof GamesTempleRunRoute
  '/games/': typeof GamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/choose-college'
    | '/profile'
    | '/games/color-chakra'
    | '/games/divine-aim'
    | '/games/ganesh-rhythm'
    | '/games/temple-run'
    | '/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/choose-college'
    | '/profile'
    | '/games/color-chakra'
    | '/games/divine-aim'
    | '/games/ganesh-rhythm'
    | '/games/temple-run'
    | '/games'
  id:
    | '__root__'
    | '/'
    | '/choose-college'
    | '/profile'
    | '/games/color-chakra'
    | '/games/divine-aim'
    | '/games/ganesh-rhythm'
    | '/games/temple-run'
    | '/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChooseCollegeRoute: typeof ChooseCollegeRoute
  ProfileRoute: typeof ProfileRoute
  GamesColorChakraRoute: typeof GamesColorChakraRoute
  GamesDivineAimRoute: typeof GamesDivineAimRoute
  GamesGaneshRhythmRoute: typeof GamesGaneshRhythmRoute
  GamesTempleRunRoute: typeof GamesTempleRunRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-college': {
      id: '/choose-college'
      path: '/choose-college'
      fullPath: '/choose-college'
      preLoaderRoute: typeof ChooseCollegeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/color-chakra': {
      id: '/games/color-chakra'
      path: '/games/color-chakra'
      fullPath: '/games/color-chakra'
      preLoaderRoute: typeof GamesColorChakraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/divine-aim': {
      id: '/games/divine-aim'
      path: '/games/divine-aim'
      fullPath: '/games/divine-aim'
      preLoaderRoute: typeof GamesDivineAimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/ganesh-rhythm': {
      id: '/games/ganesh-rhythm'
      path: '/games/ganesh-rhythm'
      fullPath: '/games/ganesh-rhythm'
      preLoaderRoute: typeof GamesGaneshRhythmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/temple-run': {
      id: '/games/temple-run'
      path: '/games/temple-run'
      fullPath: '/games/temple-run'
      preLoaderRoute: typeof GamesTempleRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChooseCollegeRoute: ChooseCollegeRoute,
  ProfileRoute: ProfileRoute,
  GamesColorChakraRoute: GamesColorChakraRoute,
  GamesDivineAimRoute: GamesDivineAimRoute,
  GamesGaneshRhythmRoute: GamesGaneshRhythmRoute,
  GamesTempleRunRoute: GamesTempleRunRoute,
  GamesIndexRoute: GamesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
